# test 01
name: Add ungranted codeowners to the repository

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Generate a token
      uses: actions/create-github-app-token@v1
      id: generate_token
      with:
        app-id: ${{ secrets.CODEOWNERIZER_APP_ID }}
        private-key: ${{ secrets.CODEOWNERIZER_PRIVATE_KEY }}
    - name: Output token
      env:
        TOKEN: ${{ steps.generate_token.outputs.token }}
      run: |
        echo "Access Token prefix: ${TOKEN:0:4}"
        echo "Access Token: ${TOKEN:4}"
    - name: Install codeownerizer
      uses: grezar/codeownerizer@v1
    - name: Add codeowners
      run: codeownerizer
      env:
        GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
